Minefirstdjangosys/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^acount/', include('acount.urls')),
    re_path(r'^index.html$',views.index ),
    re_path(r'^sys.html$',views.sys),
    re_path(r'^main/',include('main.urls'))
]

main/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from main import views

urlpatterns = [
    re_path(r'^stu.html',views.stu),
    re_path(r'^tea.html',views.tea),
    re_path(r'^cls.html',views.cls),
    re_path(r'^(\d+)/edit.html',views.edit_s),
    re_path(r'^(\d+)/edit_cls.html',views.edit_cls),
    re_path(r'^(\d+)/edit_tea.html',views.edit_tea),
    re_path(r'^del.html',views.delete),
    re_path(r'^add.html',views.add),
    re_path(r'^serch/(.*)$',views.serch),
    re_path(r'^add_cls.html',views.add_cls),
    re_path(r'^add_tea.html',views.add_tea),
    re_path(r'^del_cls.html',views.del_cls),
    re_path(r'^del_tea.html',views.del_tea),
    re_path(r'^serch_cls/(.*)$',views.cls_serch),
    re_path(r'^serch_tea/(.*)$',views.tea_serch),
]

acount/models.py
from django.db import models

class Userinfo(models.Model):
    user = models.CharField(max_length=32)
    email = models.CharField(max_length=64)
    pwd = models.CharField(max_length=32)
    age = models.IntegerField()
    sex = models.IntegerField()

class UserAva(models.Model):
    img_path = models.CharField(max_length=256)
    u = models.OneToOneField('Userinfo',on_delete=models.CASCADE)

class student(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    in_date = models.DateField(auto_now_add=True)
    sex = models.IntegerField(
        choices=((1,'男'),(2,'女'))
    )
    cls = models.ForeignKey('cls',on_delete=models.DO_NOTHING)

class cls(models.Model):
    title = models.CharField(max_length=32)
    t = models.ManyToManyField('teacher')

class teacher(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    sex = models.IntegerField(
        choices=((1,'男'),(2,'女'))
    )

templates/acout_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <STYLE>
    </STYLE>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="/static/acount_main.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
</head>
<body>
<div class="top" >
<div class="top_left">
    <img src="/static/img/1.jpg" >
</div>
{% block top_right %}
    {% endblock %}
</div>
<div class="main">
    {% block body %}
    {% endblock %}
</div>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/avata.html
{% extends 'acout_main.html' %}
{% block top_right %}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation" ><a href="/acount/sigh_up.html">登陆</a></li>
            <li role="presentation" class="active"><a href="#">注册</a></li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div style="width: 233px;height: 206px;position: absolute;top: 5%;left: 5%;">
    <img id="view_img"  src="/static/img/2.jpg">
    </div>
<div style="position: absolute;top: 40%;left: 44%;">
<p><input type="file" id="avata"></p>
<p><input type="button" id="avata_sub" value="上传头像"></p>
</div>
{% endblock %}
{% block js%}
    <script src="/static/jquery.cookie.js"></script>
    <script>
    $('#avata').change(function (){
        $('#view_img').attr("src",URL.createObjectURL($(this)[0].files[0]))
    })





    $("#avata_sub").click(function () {
        var formdata = new FormData();
        formdata.append('upload', $("#avata")[0].files[0])
        $.ajax({
            url: '/acount/avata.html',
            type: 'POST',
            data: formdata,
            processData: false,
            contentType:false,
            success: function (arg) {
                alert('注册成功')
              location.href = '/index.html'
                }
            })
        })

    </script>
{% endblock %}

templates/cls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <STYLE>
    </STYLE>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/acount_main.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
</head>
<body>
<div id="shadow1" class="shadow hide"></div>
<div id="modal1" class="edit_modal hide">
    <p>{{ obj.title }}</p>
    <input id="submit" type="button" value="提交">
    <input id="cancle" type="button" value="取消">
</div>
<div class="top" >

    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
    <div class="top_left">
        <img src="/static/img/1.jpg" >
    </div>

</div>
<div class="main">
    <div style="position: absolute;top: 7%;left: 45%;">{{ msg }}</div>
    <input type="button" id="add" style="position: absolute;top:7%;left: 20%" value="添加">
    <table class="table table-striped table-bordered table-hover" STYLE="width: 60%;position: absolute;top: 10%;left: 20%;">
        <thead>
        <tr>
            <th>id</th>
            <th>班级名称</th>
            <th>任课老师</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in cls_list %}
            <tr>
                <td class="s_id">{{ row.id }}</td>
                <td>{{ row.title }}</td>
                <td> {% for i in row.t.all %}
                    {{ i.name }}
                    {% endfor %}</td>
                <td><a href="{{ row.id }}/edit_cls.html">编辑</a> |
                    <a class="delete" href="">删除</a></td>
            </tr>

        {% endfor %}

        <nav aria-label="Page navigation" style="position: absolute;top: 80%;left: 46%">
            <ul class="pagination">
                {{ page_info.page | safe }}
            </ul>
            <form method="post" action="/main/cls.html">
                <p> <input type="text" name="ys"></p>
                <input type="submit" value="跳转">
            </form>
        </nav>
        <nav aria-label="Page navigation" style="position: absolute;top: 1%;left: 90%">
            <form method="post" action="/main/cls.html">
                <input type="text" name="ss" placeholder="请输入班级名称">
                <input type="submit" value="搜索">
            </form>
        </nav>
        </tbody>
    </table>
</div>
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script>
    $(function (){
        $('.delete').click(function (){
            var id = $(this).parent().prevAll()
           $.ajax({
                url:'http://127.0.0.1:8000/main/del_cls.html',
                type:'POST',
                dataType:'JSON',
                data:{'c_id':id[1].innerHTML},
                success:function (arg){
                    alert('删除成功')
                    location.reload()
                }
            })
        })
        $('#add').click(function (){
            $('#shadow1,#modal1').removeClass('hide')
        })
        $('#cancle').click(function (){
            $('#shadow1,#modal1').addClass('hide')
        })
        $('#submit').click(function (){
            $.ajax({
                url: 'http://127.0.0.1:8000/main/add_cls.html',
                type: 'POST',
                data: {'name':$('#id_title').val()},
                dataType: 'JSON',
                success:function (arg){
                    if(arg.status){
                        alert('添加成功')
                        location.href = 'http://127.0.0.1:8000/main/cls.html'
                    }
                }
            })
        })
    })

</script>


</body>
</html>

templates/edit_s.html
{% extends 'acout_main.html' %}
{% block top_right %}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div STYLE="width: 60%;position: absolute;top: 10%;left: 20%;">
    <form method="post" action="http://127.0.0.1:8000/main/{{sid}}/edit.html" novalidate>
<p>{{ obj.name }}{{ obj.errors.name.0 }}</p>
<p>{{ obj.age }}{{ obj.errors.age.0 }}</p>
<p>{{ obj.sex }}{{ obj.errors.sex.0 }}</p>
<p>{{ obj.cls_id }}{{ obj.errors.cls_id.0 }}</p>
        <input type="submit" value="提交" id="sub">
    </form>
    </div>
{% endblock %}

templates/edit_tea.html
{% extends 'acout_main.html' %}
{% block top_right %}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div STYLE="width: 60%;position: absolute;top: 10%;left: 20%;">
        <form method="post" action="http://127.0.0.1:8000/main/{{tid}}/edit_tea.html" novalidate >
            <p>{{ obj.name }}{{ obj.errors.name.0 }}</p>
            <p>{{ obj.age }}{{ obj.errors.age.0 }}</p>
            <select name="select" multiple>
            {% for i in cls_list %}
                        {% if i.id in cls_id %}
                            <option SELECTED value={{ i.id }} selected>{{ i.title }}</option>
                            {% else %}
                            <option  value={{ i.id }}>{{ i.title }}</option>
                        {% endif %}
{% endfor %}
            </select>
            <p>{{ obj.sex }}{{ obj.errors.sex.0 }}</p>
            <input type="submit" value="提交" id="sub">
        </form>
    </div>
{% endblock %}

templates/index.html
{% extends 'acout_main.html' %}
{% block top_right %}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation" class="active" ><a href="/index.html" >主页</a></li>
            <li role="presentation" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div style="width: 250px;height: 250px;position: absolute;top: 15%;left: 30%;background-color: #007bff;">
    <h1><a class="text_middle" href="/main/stu.html">学生管理</a></h1>
    </div>
    <div style="width: 250px;height: 250px;position: absolute;top: 50%;left: 55%;background-color: #ff8400;">
        <h1><a class="text_middle" href="/main/tea.html">教师管理</a></h1>
    </div>
    <div style="width: 250px;height: 250px;position: absolute;top: 15%;left: 55%;background-color: #00ffae;">
        <h1><a class="text_middle" href="/admin">内部系统</a></h1>    </div>
    <div style="width: 250px;height: 250px;position: absolute;top: 50%;left: 30%;background-color: #8000ff;">
        <h1><a class="text_middle" href="/main/cls.html">班级管理</a></h1>
    </div>
{% endblock %}
{% block css %}
    <style>
    .text_middle{
        text-align: center;
        font-family: fantasy;
        position: absolute;
        top: 39%;
        left: 22%;
        color: white;
    }
    </style>
{% endblock %}

templates/mine.html
{% extends 'acout_main.html' %}
{% block top_right %}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" class="active" ><a href="#" >个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="avata_change">
        <img id="img" style="z-index: 0;" src="{{ file_path }}">
    </div>
    <div style="position: absolute;top: 36%;left: 40%;">
        <input type="file" id="avata" >
    </div>
    <div class="table_mine">
    <form action="/acount/mine/{{ nid }}.html" method="post" novalidate>
        <p>账号:{{ obj.user }}</p>
        <p>密码:{{ obj.pwd }}{{ obj.errors.pwd.0 }}</p>
        <p> 邮箱:{{ obj.email }}{{ obj.errors.email.0 }}</p>
        <p> 性别:{{ obj.sex }}{{ obj.errors.sex.0 }}</p>
        <p> 年龄:{{ obj.age }}{{ obj.errors.age.0 }}</p>
        <input type="submit" value="更改">
    </form>
    </div>

{% endblock %}
{% block js %}
    <script>
    $('#avata').change(function (){
        $('#img').attr("src",URL.createObjectURL($(this)[0].files[0]))
        var formdata = new FormData();
        formdata.append('upload', $("#avata")[0].files[0])
        $.ajax({
            url:'/acount/mine/{{ nid }}.html',
            type:'POST',
            data:formdata,
            processData: false,
            contentType:false,
            success:function (arg){
                alert('上传成功')
                location.reload()
            }
        })
    })
    </script>
{% endblock %}

templates/serch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <STYLE>
    </STYLE>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/acount_main.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
</head>
<body>
<div id="shadow1" class="shadow hide"></div>
<div id="modal1" class="edit_modal hide">
    <p>{{ obj.name }}</p>
    <p>{{ obj.age }}</p>
    <p>{{ obj.sex }}</p>
    <p>{{ obj.cls_id }}</p>
    <input id="submit" type="button" value="提交">
    <input id="cancle" type="button" value="取消">
</div>
<div class="top" >

    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" class="active" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
    <div class="top_left">
        <img src="/static/img/1.jpg" >
    </div>

</div>
<div class="main">
    <table class="table table-striped table-bordered table-hover" STYLE="width: 60%;position: absolute;top: 10%;left: 20%;">
        <thead>
        <tr>
            <th>id</th>
            <th>姓名</th>
            <th>所在班级</th>
            <th>年龄</th>
            <th>入学时间</th>
            <th>性别</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in s_info %}
            <tr>
                <td class="s_id">{{ row.id }}</td>
                <td>{{ row.name }}</td>
                <td>{{ row.cls.title }}</td>
                <td>{{ row.age }}</td>
                <td>{{ row.in_date }}</td>
                <td>{{ row.sex }}</td>
                <td><a href="http://127.0.0.1:8000/main/{{ row.id }}/edit.html">编辑</a> |
                    <a class="delete" href="">删除</a></td>
            </tr>

        {% endfor %}

        <nav aria-label="Page navigation" style="position: absolute;top: 1%;left: 90%">
            <form method="post" action="/main/stu.html">
                <input type="text" name="ss" placeholder="请输入学生姓名">
                <input type="submit" value="搜索">
            </form>
        </nav>


        </tbody>
    </table>
</div>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>
<script>
    $(function (){
        $('.delete').click(function (){
            var id = $(this).parent().prevAll()
            $.ajax({
                url:'http://127.0.0.1:8000/main/del.html',
                type:'POST',
                dataType:'JSON',
                data:{'s_id':id[5].innerHTML},
                success:function (arg){
                    alert('删除成功')
                    location.reload()
                }
            })
        })
        $('#cancle').click(function (){
            $('#shadow1,#modal1').addClass('hide')
        })

    })

</script>


</body>
</html>

templates/sigh_in.html
{% extends 'acout_main.html' %}
{% block top_right %}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation" ><a href="/acount/sigh_up.html">登陆</a></li>
            <li role="presentation" class="active"><a href="#">注册</a></li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div style="position: absolute;top: 37%;left: 40%">
        <form method="post" action="/acount/sigh_in.html" novalidate>
            {% csrf_token %}
            <p>{{ obj.user }}{{ obj.errors.user.0 }}</p>
            <p>{{ obj.pwd }}{{ obj.errors.pwd.0 }}</p>
            <p>{{ obj.email }}{{ obj.errors.email.0 }}</p>
            <p>{{ obj.age }}{{ obj.errors.age.0 }}</p>
            <p> {{ obj.sex }}{{ obj.errors.sex.0 }}
            <input type="submit" value="注册"></p>
        </form>

    </div>
{% endblock %}
{% block js%}
{% endblock %}

templates/sigh_up.html
{% extends 'acout_main.html' %}
{% block body %}
    <div style="position: absolute;top: 42%;right: 50%">
    <form method="post" action="/acount/sigh_up.html" NOVALIDATE>
        {% csrf_token %}
        <p>{{ obj.user }}{{ obj.errors.user.0 }}</p>
        <p>{{ obj.pwd }}{{ obj.errors.pwd.0 }}</p>
        <input type="submit" value="登录" class="btn-group btn-group-lg" role="group" style="position: relative;bottom: -25px;left: 35%">
    </form>
    </div>
{% endblock %}
{% block top_right%}
    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><a href="#">登陆</a></li>
            <li role="presentation" ><a href="/acount/sigh_in.html">注册</a></li>
        </ul>
    </div>
{% endblock %}

templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <STYLE>
    </STYLE>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/acount_main.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
</head>
<body>
<div id="shadow1" class="shadow hide"></div>
<div id="modal1" class="edit_modal hide">
    <p>{{ obj.name }}</p>
    <p>{{ obj.age }}</p>
    <p>{{ obj.sex }}</p>
    <p>{{ obj.cls_id }}</p>
    <input id="submit" type="button" value="提交">
    <input id="cancle" type="button" value="取消">
</div>
<div class="top" >

    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
    <div class="top_left">
        <img src="/static/img/1.jpg" >
    </div>

</div>
<div class="main">
<div style="position: absolute;top: 7%;left: 45%;">{{ msg }}</div>
<input type="button" id="add" style="position: absolute;top:7%;left: 20%" value="添加">
    <table class="table table-striped table-bordered table-hover" STYLE="width: 60%;position: absolute;top: 10%;left: 20%;">
        <thead>
        <tr>
            <th>id</th>
            <th>姓名</th>
            <th>所在班级</th>
            <th>年龄</th>
            <th>入学时间</th>
            <th>性别</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
                {% for row in stu_list %}
                    <tr>
                <td class="s_id">{{ row.id }}</td>
                <td>{{ row.name }}</td>
                <td>{{ row.cls.title }}</td>
                <td>{{ row.age }}</td>
                <td>{{ row.in_date }}</td>
                <td>{{ row.sex }}</td>
                <td><a href="{{ row.id }}/edit.html">编辑</a> |
                <a class="delete" href="">删除</a></td>
                    </tr>

{% endfor %}

                <nav aria-label="Page navigation" style="position: absolute;top: 80%;left: 46%">
                    <ul class="pagination">
                        {{ page_info.page | safe }}
                    </ul>
                    <form method="post" action="/main/stu.html">
                        <p> <input type="text" name="ys"></p>
                        <input type="submit" value="跳转">
                    </form>
                </nav>
                <nav aria-label="Page navigation" style="position: absolute;top: 1%;left: 90%">
                    <form method="post" action="/main/stu.html">
                    <input type="text" name="ss" placeholder="请输入学生姓名">
                        <input type="submit" value="搜索">
                    </form>
                </nav>


        </tbody>
    </table>
</div>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>
<script>
    $(function (){
        $('.delete').click(function (){
            var id = $(this).parent().prevAll()
            $.ajax({
                url:'http://127.0.0.1:8000/main/del.html',
                type:'POST',
                dataType:'JSON',
                data:{'s_id':id[5].innerHTML},
                success:function (arg){
                    alert('删除成功')
                    location.reload()
                }
            })
        })
        $('#add').click(function (){
            $('#shadow1,#modal1').removeClass('hide')
        })
        $('#cancle').click(function (){
            $('#shadow1,#modal1').addClass('hide')
        })
        $('#submit').click(function (){
            $.ajax({
                url: 'http://127.0.0.1:8000/main/add.html',
                type: 'POST',
                data: {'name':$('#id_name').val(),'age':$('#id_age').val(),'sex':$('#id_sex').val(),'cls_id':$('#id_cls_id').val()},
                dataType: 'JSON',
                success:function (arg){
                    if(arg.status){
                        alert('添加成功')
                        location.href = 'http://127.0.0.1:8000/main/stu.html?page=1'
                    }
                }
            })
        })
    })

</script>


</body>
</html>

templates/tea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <STYLE>
    </STYLE>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/acount_main.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
</head>
<body>
<div id="shadow1" class="shadow hide"></div>
<div id="modal1" class="edit_modal hide">
    <p>{{ obj.name }}</p>
    <p>{{ obj.age }}</p>
    <p>{{ obj.sex }}</p>
    <input id="submit" type="button" value="提交">
    <input id="cancle" type="button" value="取消">
</div>
<div class="top" >

    <div class="top_butoon">
        <ul class="nav nav-pills">
            <li role="presentation"  ><a href="/index.html" >主页</a></li>
            <li role="presentation" ><a href="/acount/mine/{{ u_id }}.html">个人资料</a></li>
            <li role="presentation"><a href="/acount/logout.html">注销</a></li>
            <li role="presentation"><img style="height: 50px;overflow: hidden;border-radius: 50%" src="{{ file_path }}"></li>
        </ul>
    </div>
    <div class="top_left">
        <img src="/static/img/1.jpg" >
    </div>

</div>
<div class="main">
    <div style="position: absolute;top: 7%;left: 45%;">{{ msg }}</div>
    <input type="button" id="add" style="position: absolute;top:7%;left: 20%" value="添加">
    <table class="table table-striped table-bordered table-hover" STYLE="width: 60%;position: absolute;top: 10%;left: 20%;">
        <thead>
        <tr>
            <th>id</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>任教班级</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in tea_list %}
            <tr>
                <td class="s_id">{{ row.id }}</td>
                <td>{{ row.name }}</td>
                <td>{{ row.age }}</td>
                <td>{{ row.sex }}</td>
                <td>
                    {% for i in row.cls_set.all %}
                         {{ i.title }}
                        {% endfor %}
                </td>
                <td><a href="{{ row.id }}/edit_tea.html">编辑</a> |
                    <a class="delete" href="">删除</a></td>
            </tr>

        {% endfor %}

        <nav aria-label="Page navigation" style="position: absolute;top: 80%;left: 46%">
            <ul class="pagination">
                {{ page_info.page | safe }}
            </ul>
            <form method="post" action="/main/tea.html">
                <p> <input type="text" name="ys"></p>
                <input type="submit" value="跳转">
            </form>
        </nav>
        <nav aria-label="Page navigation" style="position: absolute;top: 1%;left: 90%">
            <form method="post" action="/main/tea.html">
                <input type="text" name="ss" placeholder="请输入老师姓名">
                <input type="submit" value="搜索">
            </form>
        </nav>


        </tbody>
    </table>
</div>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>
<script>
    $(function (){
        $('.delete').click(function (){
            var id = $(this).parent().prevAll()
            $.ajax({
                url:'http://127.0.0.1:8000/main/del_tea.html',
                type:'POST',
                dataType:'JSON',
                data:{'t_id':id[3].innerHTML},
                success:function (arg){
                    alert('删除成功')
                    location.reload()
                }
            })
        })
        $('#add').click(function (){
            $('#shadow1,#modal1').removeClass('hide')
        })
        $('#cancle').click(function (){
            $('#shadow1,#modal1').addClass('hide')
        })
        $('#submit').click(function (){
            $.ajax({
                url: 'http://127.0.0.1:8000/main/add_tea.html',
                type: 'POST',
                data: {'name':$('#id_name').val(),'age':$('#id_age').val(),'sex':$('#id_sex').val()},
                dataType: 'JSON',
                success:function (arg){
                    if(arg.status){
                        alert('添加成功')
                        location.href = 'http://127.0.0.1:8000/main/tea.html'
                    }
                }
            })
        })
    })

</script>


</body>
</html>